// Repository
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const ASSET_REPOSITORY = 'ASSET_REPOSITORY';
export const DEBT_REPOSITORY = 'DEBT_REPOSITORY';
export const CASHFLOWIN_REPOSITORY = 'CASHFLOWIN_REPOSITORY';
export const CASHFLOWOUT_REPOSITORY = 'CASHFLOWOUT_REPOSITORY';
export const CATEGORY_REPOSITORY = 'CATEGORY_REPOSITORY';
export const POCKET_REPOSITORY = 'POCKET_REPOSITORY';
export const TRANSFER_REPOSITORY = 'TRANSFER_REPOSITORY';
